services:
  db:
    image: mariadb:10.4.27
    command: --lower_case_table_names=1
    volumes:
      - civilprotect_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d:ro
    env_file: ".env"
    healthcheck:
      test: mysql --user=root --password=waynejones --execute="SHOW DATABASES";
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s
      
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db: 
        condition: service_healthy
volumes:
  civilprotect_data: